services:
  postgres:
    image: postgres:14
    container_name: bookstore_postgres
    environment:
      POSTGRES_DB: book_store_db
      POSTGRES_PASSWORD: bookstore
      POSTGRES_USER: bookstore
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
